### ISSUE TITLE
Uppercase Package Names

### ISSUE THREAD

**Issue by stefankoegl** [dragontek/mygpoclient-java#1]
Might be good to raise such breaking issues early: aren't upper-case packages names (eg com.dragontek.mygpoclient.Json) quite uncommon in Java?

**Comment by jmondragon** [comment]
Thank you, I think you're right.  Convention is lowercase package names and camelcase classes.  I'll get those fixed.

**Comment by jmondragon** [comment]
Updated all package names to follow Java convention.
